name: NormalizedDrops
description: Improve the fairness of drops and make PvE on a PvP server more meaningful.
author: verrier, megabytes
website: http://minecarts.com/

main: com.minecarts.normalizeddrops.NormalizedDrops
version: ${pom.version}

commands:
  normalizeddrops:
    aliases: [ndrop, ndrops, nd]
    description: Primary command to interact with NormalizedDrops 
    usage: /<command> [reload]
    
permissions:
  normalizeddrops:
    reload:
      description: Reload NormalizedDrops config.yml
      default: op