name: NormalizedDrops
main: com.minecarts.normalizeddrops.NormalizedDrops
version: ${pom.version}
website: http://minecarts.com/
author: verrier, megabytes
description: Improve the fairness of drops and make PvE on a PvP server more meaningful.

commands:
  moralizeddrops:
    aliases: [ndrop, ndrops, nd]
    description: Primary command to interact with NormalizedDrops 
    usage: /<command> [reload]