name: NormalizedDrops
main: com.minecarts.normalizeddrops.NormalizedDrops
version: ${pom.version}
website: http://minecarts.com
author: Verrier
description: >
             Improve the fairness of drops and make PvE on a PvP server more worthwhile
commands:
  moralizeddrops:
    aliases: [ndrop, ndrops, nd]
    description: Main command to interact with NormalizeDdrops 
    usage: /<command> [reload]