name: NormalizedDrops
main: com.minecarts.normalizeddrops.NormalizedDrops
version: 1.0.2
website: http://minecarts.com
author: Verrier
description: >
             Improve the fairness of drops and make PvE on a PvP server more worthwhile
commands:
  ndrop:
    description: Main command to interact with NormalizeDdrops 
    usage: /<command> [reload]